version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_sivs_diary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sivs_2024!
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  redis:
    image: "redis:alpine"
    command: /bin/sh -c "redis-server --requirepass sivs_2024"
