spring:
  application:
    name: authentication
  # Diary DB
  datasource:
    url: jdbc:postgresql://localhost:5432/db_sivs_diary
    username: postgres
    password: sivs_2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Thymeleaf
  web:
    resources:
      static-locations: classpath:/static/
  # Redis Session
#  data:
#      redis:
#        url: redis://localhost:6379
#        host: localhost
#        password: session
#        port: 6379