spring:
  application:
    name: authentication
  # Diary DB
  datasource:
    url: jdbc:postgresql://${postgres.route:localhost}:5432/db_sivs_diary
    username: postgres
    password: sivs_2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Thymeleaf
  web:
    resources:
      static-locations: classpath:/static/
  # Redis Session
  data:
      redis:
        host: ${redis.route:localhost}
        port: 6379
        password: sivs_2024