spring:
  application:
    name: authentication
  datasource:
    # if application started from docker-compose use env variable from compose or if started from ide use localhost
    url: jdbc:postgresql://${postgres.route:localhost}:5432/db_sivs_diary
    username: postgres
    password: sivs_2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org:
      springframework:
        security: TRACE
